import type { NextPage } from 'next'
import Head from 'next/head'
import HomeModule from 'modules/home'

import 'primereact/resources/themes/saga-blue/theme.css'
import 'primereact/resources/primereact.min.css'
import 'primeicons/primeicons.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeModule />
    </>
  )
}

export default Home
